# Generated by Django 3.0.5 on 2020-04-13 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(default='', max_length=30, null=True)),
                ('last_name', models.CharField(default='', max_length=30, null=True)),
                ('birth_day', models.DateField(default='', max_length=20, null=True)),
                ('minor', models.CharField(default='', max_length=20, null=True)),
                ('phone', models.CharField(default='', max_length=20, null=True)),
                ('email', models.CharField(default='', max_length=40, null=True)),
                ('status', models.CharField(default='', max_length=30, null=True)),
                ('marketing', models.CharField(default='', max_length=20, null=True)),
                ('guardian_id', models.CharField(default='', max_length=20, null=True)),
                ('address1', models.CharField(default='', max_length=20, null=True)),
                ('address2', models.CharField(default='', max_length=20, null=True)),
                ('city', models.CharField(default='', max_length=20, null=True)),
                ('state', models.CharField(default='', max_length=20, null=True)),
                ('zip_code', models.CharField(default='', max_length=20, null=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=50, null=True)),
            ],
            options={
                'db_table': 'waiver',
            },
        ),
        migrations.CreateModel(
            name='SignedWaiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_date', models.DateField(default='', max_length=20, null=True)),
                ('contact', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Waiver.Contact')),
                ('waiver', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Waiver.Waiver')),
            ],
            options={
                'db_table': 'signed_waiver',
            },
        ),
    ]
